### ISSUE TITLE
location based product availability.

### ISSUE THREAD

**Issue by eatablewonderful** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#112]
What if vendor wants to sell particular product at particular location so customer will enter location or his location will be taken through gps permission and another location will be selected and products sold only between this two locations will be shown.

**Comment by kirilkirkov** [comment]
@eatablewonderful This is an interesting feature. I'll think about it!

**Comment by kirilkirkov** [comment]
the problem here is that a third party must be used, which is not very certain, but I will think of an option.

**Comment by kirilkirkov** [comment]
@eatablewonderful 
This is good functionality, but I will not add it because of the need for a third party to work properly.
The easiest way to add it is:

1. Add new field to products add/update (add in admin publish.php view and database - products)
2. Add function (maybe helper) who get visitor ip and post to - http://ipinfo.io/$VISITOR_IP/geo and parse City from returned Json
3. in Public_model add to mysql query statement to get products only with this City.

**Comment by eatablewonderful** [comment]
Actually you can used gps inbuilt in phone to know location
it is more precise than one through ip addresses.

**Comment by kirilkirkov** [comment]
@eatablewonderful 
It is easier to put a drop-down menu from which to choose the country for which they want the delivery (on checkout page) and there are no countries that are not supported ;)

GPS location find will work only for customers who have a location enabled and browse from phone, which is a limitation and is not practical.

Using a third party is a problem because when the api-to service stops working, your site also stops and you can not understand unless you have a checker to follow up on it.
