### ISSUE TITLE
Nginx configuration 

### ISSUE THREAD

**Issue by tarek369** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#131]
Hi can someone please post the nginx configuration, as it will be in /var/www/html/shop
i tried many things but it cant read the CSS files and any / after the shop

**Comment by absalam48** [comment]
remove from .htaccess file "RewriteBase /" line because css and js files will not be loaded!

**Comment by kirilkirkov** [comment]
Little explain for installation - if you paste installation of project in directory something like http://localhost/SHOP, you must set this directory to application/config/config.php - $config['base_url'] = 'http://localhost/SHOP'; and must remove from .htaccess file "RewriteBase /" line because css and js files will not be loaded! But you must know that the best way to install this platform is to set it in root http://localhost directory or if you want to be in other directory just set virtual host for this and point him to there. (example: http://shop.dev - point to localhost/shop directory). How to create virtual hosts you can read here: http://goo.gl/UvpYMG
@tarek369
