### ISSUE TITLE
template modifications

### ISSUE THREAD

**Issue by Kimson11** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#159]
i have removed RewriteBase / line already everything is working fine it just doesnt load the extra css code for the modifiactions i made

**Comment by kirilkirkov** [comment]
@Kimson11 Do you read this:

Little explanation about the installation - if you paste installation of project in directory something like http://localhost/SHOP, you must set this directory to application/config/config.php - $config['base_url'] = 'http://localhost/SHOP'; and must remove from .htaccess file "RewriteBase /" line because css and js files will not be loaded! But you must know that the best way to install this platform is to set it in root http://localhost directory or if you want to be in other directory just set virtual host for this and point him to there. (example: http://shop.dev - point to localhost/shop directory). How to create virtual hosts you can read here: http://goo.gl/UvpYMG

?

**Comment by Kimson11** [comment]
yes installation procedure in the readme file
