### ISSUE TITLE
Having wrong final sum during checkout

### ISSUE THREAD

**Issue by studuino** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#169]
Hi,
During the checkout using discount coupon code, 
there's something wrong with the calculation in both (%) and (amount).
I am having wrong final sum.
Template Used : redlabel

Discount type : (%)
![image](https://user-images.githubusercontent.com/2291009/82506894-efa74200-9b26-11ea-87cb-18a55bd5f0d6.png)

Discount type : (Amount)
![image](https://user-images.githubusercontent.com/2291009/82506970-136a8800-9b27-11ea-801d-c3dc99103643.png)

Discount Coupons
![image](https://user-images.githubusercontent.com/2291009/82507003-28471b80-9b27-11ea-9b1a-f8bc8fc69724.png)

Thanks.

**Comment by muratanka** [comment]
Because of the comma in the amount part. PHP doesn’t accept the digit after comma as integer. Easiest way is turning the whole amount to integer before calculation. You can search Google by these keywords “ php type conversion “. Before calculation the amount should be converted to integer first.

iPhone’umdan gönderildi

studuino <notifications@github.com> şunları yazdı (21 May 2020 02:23):

﻿

Hi,
During the checkout using discount coupon code,
there's something wrong with the calculation in both (%) and (amount).
I am having wrong final sum.

Discount type : (%)
[image]<https://user-images.githubusercontent.com/2291009/82506894-efa74200-9b26-11ea-87cb-18a55bd5f0d6.png>

Discount type : (Amount)
[image]<https://user-images.githubusercontent.com/2291009/82506970-136a8800-9b27-11ea-801d-c3dc99103643.png>

Discount Coupons
[image]<https://user-images.githubusercontent.com/2291009/82507003-28471b80-9b27-11ea-9b1a-f8bc8fc69724.png>

Thanks.

**Comment by studuino** [comment]
Hi @muratanka,
Thank you for your kind suggestion.
After the type conversion from text to float. it works as expected.
