### ISSUE TITLE
my appearance is disheveled, not like in your preview

### ISSUE THREAD

**Issue by irvanthole** [kirilkirkov/Ecommerce-CodeIgniter-Bootstrap#176]
I found a problem at the beginning of the beginning, when I load my url localhost / SHOP, my appearance is disheveled, not like in your preview and when I click on another page like chaeckout, the object not found appears. Could you help me. I have changed the baseurl in the config but it still shows up in disarray.
![problem](https://user-images.githubusercontent.com/37149674/83951673-664d7a80-a85d-11ea-8671-6ebfd0305562.png)
![problem chackout](https://user-images.githubusercontent.com/37149674/83951706-99900980-a85d-11ea-8166-7efd0508c919.png)

**Comment by kirilkirkov** [comment]
@irvanthole  Check readme file.

"if you paste installation of project in directory something like http://localhost/SHOP, you must set this directory to application/config/config.php - $config['base_url'] = 'http://localhost/SHOP'; and must remove from .htaccess file "RewriteBase /" line because css and js files will not be loaded"

**Comment by irvanthole** [comment]
Thank you for your help

**Comment by bpiltz** [comment]
Just installed locally according to the readme an I have the same issue. The "RewriteBase /" is not in the .htaccess anyways. IT seems the router is not ok. Or the config.php file is not loaded properly. It is always the same no matter what I put into the "base_url" field. I tried different approaches with the virtual host as a root url but no chance. Something is broken it seems. What php should be used by the way? I had 7.2 now.
